services:
  frontend:
    image: kamachat-frontend:latest
    ports:
      - "3000:80"
  backend:
    environment:
      CONFIG_PATH: /app/configs/config_aws.toml
    volumes:
      - ./static:/app/static
      - ./logs:/app/logs
      - /etc/letsencrypt:/etc/letsencrypt:ro
